language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "Building images"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # Tagging
  - docker tag udagram-api-feed juandavidtorres/udagram-api-feed:v1
  - docker tag udagram-api-user juandavidtorres/udagram-api-user:v1
  - docker tag udagram-frontend juandavidtorres/udagram-frontend:v1
  - docker tag udagram-reverseproxy juandavidtorres/udagram-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Push
  - docker push juandavidtorres/udagram-api-feed:v1
  - docker push juandavidtorres/udagram-api-user:v1
  - docker push juandavidtorres/udagram-frontend:v1
  - docker push juandavidtorres/udagram-reverseproxy:v1